### ISSUE TITLE
pclean crashes on hosptial data

### ISSUE THREAD

**Issue by ThomasColthurst** [probcomp/hierarchical-irm#151]
Run when running on the 10 line CSV file version with
./bazel-bin/pclean/pclean --schema=assets/hospitals.schema --obs=assets/hospital_dirty.10.csv --iters=5

it crashes with
pclean: distributions/stringcat.cc:11: int StringCat::string_to_index(const std::string&) const: Assertion `false' failed.

That's the line where we assert that the input string to string_to_index is one of the strings the StringCat distribution is over.

This happens during inference, during transition_latent_values for the relation Hospital:owner.

Debugging reveals that the string being passed to string_to_index is non-printable nonsense ("��.�tU").

**Comment by ThomasColthurst** [comment]
Approximate call chain is

transition_latent_values
latent_values_incremental_logp
clean_relation::incorporate_to_cluster with base_items=[8, 8, 8, 8] and value="government"
clusters.at([1, 1, 0, 0])->incorporate("goverment")
stringcat::incorporate("�b��V")

So there are two really weird things going on here:
1) clean_relations::incorporate_to_cluster passes a perfectly valid string to stringcat::incorporate, but inside of stringcat::incorporate it is corrupted.

2) "government" isn't actually a valid choice from this particular stringcat distribution.  As specified in the schema, and verified by printing out the strings vector inside the stringcat distribution, the valid choices are
 government - federal
government - hospital district or authority
government - local
government - state
government - federal
proprietary
voluntary non-profit - church
voluntary non-profit - other
voluntary non-profit - private

I thought that problem 1 might have been caused by accessing through an invalid cluster, but I printed out the list of cluster keys and confirmed that [1, 1, 0, 0] is one of them.

+emilyfertig in case she has any ideas

**Comment by emilyfertig** [comment]
This is weird...if you have debugging code with print statements etc. that would be useful as a starting point, could you push it to a branch?

**Comment by ThomasColthurst** [comment]
> This is weird...if you have debugging code with print statements etc. that would be useful as a starting point, could you push it to a branch?

Sure; I just pushed 080924-thomaswc-speed which has the printf's and new asset files.

**Comment by emilyfertig** [comment]
On line 12 of `stringcat.cc` the second argument to `printf` was missing, and when I add it back, it prints `government` as expected, so that demystifies 1 at least. Still not sure about 2, it looks like we're handling the space character wrong somewhere?

```
about to incorporate value government
Could not find string `government` in list of strings:
government - federal
government - hospital district or authority
government - local
government - state
government - federal
proprietary
voluntary non-profit - church
voluntary non-profit - other
voluntary non-profit - private
pclean: distributions/stringcat.cc:17: int StringCat::string_to_index(const std::string&) const: Assertion `false' failed.
Aborted
```

**Comment by emilyfertig** [comment]
I just found this too and was about to comment, thanks for the fix!

**Comment by ThomasColthurst** [comment]
After the fix for the above error, we have a new error:

terminate called after throwing an instance of 'std::domain_error'
  what():  Bad argument in __cyl_bessel_i.

This must be coming from Skellam::logp, the only place that calls cyl_bessel_i.
